#!/usr/bin/env python3
"""Build guide sections or the canonical combined publication."""
from __future__ import annotations

import argparse
from datetime import datetime, timezone
import hashlib
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import time

from guide_validation import validate_guide

SCRIPT_DIR = Path(__file__).resolve().parent
GUIDE_ROOT = SCRIPT_DIR.parent
REPO_ROOT = GUIDE_ROOT.parent
TEMPLATE = GUIDE_ROOT / "templates" / "guide-template.tex"
LICENSE_FILE = REPO_ROOT / "metadata" / "licenses.yml"

sys.path.insert(0, str(REPO_ROOT / "python_scripts"))
from license_metadata import load_license_metadata  # noqa: E402


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def tex_escape(value: str) -> str:
    return "".join({"\\": r"\textbackslash{}", "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#", "_": r"\_", "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}", "^": r"\textasciicircum{}"}.get(char, char) for char in value)


def version_line(name: str) -> str:
    executable = shutil.which(name)
    if not executable:
        return "not found"
    proc = subprocess.run([executable, "--version"], capture_output=True, text=True, timeout=10)
    return ((proc.stdout or proc.stderr).splitlines() or [executable])[0].strip()


def order_entries(root: Path) -> list[str]:
    return [line.strip() for line in (root / "manuscript" / "order.txt").read_text(encoding="utf-8").splitlines() if line.strip() and not line.strip().startswith("#")]


def render_markdown(root: Path, manuscript: Path, output: Path) -> None:
    proc = subprocess.run(["pandoc", "-f", "markdown", "-t", "latex", str(manuscript)], cwd=root.parent, capture_output=True, text=True)
    if proc.returncode:
        raise RuntimeError(proc.stderr or f"Pandoc failed for {manuscript}")
    import re
    lines: list[str] = []
    for line in proc.stdout.splitlines():
        match = re.fullmatch(
            r"\s*(?:\[\[|\{\[\}\{\[\})REPORTKIT-VISUAL:fig:"
            r"([a-z0-9]+(?:-[a-z0-9]+)*)"
            r"(?:\]\]|\{\]\}\{\]\})\s*",
            line,
        )
        if match:
            fragment = root / "fragments" / f"fig-{match.group(1)}.tex"
            if not fragment.is_file():
                raise RuntimeError(f"missing fragment: {fragment}")
            lines.append(fragment.read_text(encoding="utf-8"))
        else:
            lines.append(line)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_metadata(path: Path, *, title: str, subtitle: str, author: str, version: str, combined: bool, license_values: dict[str, str], cover_name: str | None, uses_tables: bool, uses_code: bool) -> None:
    lines = [
        "% Generated by guide-build.py; do not edit.",
        "\\newif\\ifGuideUsesTables",
        "\\GuideUsesTablestrue" if uses_tables else "\\GuideUsesTablesfalse",
        "\\newif\\ifGuideUsesCode",
        "\\GuideUsesCodetrue" if uses_code else "\\GuideUsesCodefalse",
        "\\newif\\ifGuideIsCombined",
        "\\newif\\ifGuideHasCover",
        "\\GuideIsCombinedtrue" if combined else "\\GuideIsCombinedfalse",
        "\\GuideHasCovertrue" if cover_name else "\\GuideHasCoverfalse",
        f"\\newcommand{{\\GuideTitle}}{{{tex_escape(title)}}}",
        f"\\newcommand{{\\GuideSubtitle}}{{{tex_escape(subtitle)}}}",
        f"\\newcommand{{\\GuideAuthor}}{{{tex_escape(author)}}}",
        f"\\newcommand{{\\GuideVersion}}{{{tex_escape(version)}}}",
        "\\newcommand{\\GuideDate}{" + datetime.now().strftime("%-d %B %Y") + "}",
        "\\newcommand{\\GuideLeftHeader}{REPORTKIT / DATA ENGINEERING GUIDE}",
        "\\newcommand{\\GuideFooter}{Data Engineering Guide}",
        "\\newcommand{\\GuideSubject}{Core concepts, systems, pipelines, and production practices for data engineering.}",
        "\\newcommand{\\GuideKeywords}{data engineering, data systems, pipelines, storage, orchestration, data quality}",
        "\\newcommand{\\GuideProjectURL}{https://github.com/iancwm/report-kit}",
        f"\\newcommand{{\\GuideContentLicense}}{{{tex_escape(license_values['content_license'])}}}",
        f"\\newcommand{{\\GuideContentLicenseURL}}{{{license_values['content_license_url']}}}",
        f"\\newcommand{{\\GuideCoverPath}}{{{cover_name or ''}}}",
        "\\newcommand{\\GuideDisclaimer}{Educational material only. Verify examples against current documentation; this guide is not operational, financial, legal, or security advice.}",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def run(command: list[str], cwd: Path, log: Path) -> int:
    with log.open("a", encoding="utf-8") as stream:
        stream.write("$ " + " ".join(command) + "\n")
        proc = subprocess.run(command, cwd=cwd, stdout=stream, stderr=subprocess.STDOUT, text=True)
    return proc.returncode


def build(args: argparse.Namespace) -> int:
    source_root = Path(args.source_root).resolve() if args.source_root else GUIDE_ROOT
    validation = validate_guide(source_root)
    if not validation.ok:
        for error in validation.errors:
            print(f"guide validation: {error}", file=sys.stderr)
        return 1
    try:
        license_values = load_license_metadata(LICENSE_FILE)
    except (OSError, ValueError) as exc:
        print(f"licensing: {exc}", file=sys.stderr)
        return 1
    entries = order_entries(source_root)
    if args.mode == "section":
        chosen = args.section
        if not chosen:
            print("--section is required in section mode", file=sys.stderr)
            return 2
        manuscripts = [Path(chosen)]
    else:
        manuscripts = [Path(entry) for entry in entries]
    for manuscript in manuscripts:
        if not (source_root / "manuscript" / manuscript).is_file():
            print(f"missing manuscript: {manuscript}", file=sys.stderr)
            return 1
    stamp = time.strftime("%Y%m%d-%H%M%S")
    output = GUIDE_ROOT / "build" / ("combined" if args.mode == "combined" else f"section-{Path(manuscripts[0]).stem}-{stamp}")
    output.mkdir(parents=True, exist_ok=True)
    for path in list((REPO_ROOT / "latex_templates").glob("*.cls")) + list((REPO_ROOT / "latex_templates").glob("*.sty")):
        shutil.copy2(path, output / path.name)
    shutil.copy2(TEMPLATE, output / TEMPLATE.name)
    cover_name = None
    if args.cover:
        cover = Path(args.cover).resolve()
        if not cover.is_file() or cover.suffix.lower() != ".pdf":
            print(f"cover must be an existing PDF: {cover}", file=sys.stderr)
            return 2
        cover_name = "reportkit-cover.pdf"
        shutil.copy2(cover, output / cover_name)
    body_files = []
    for index, manuscript in enumerate(manuscripts):
        rendered = output / f"body-{index:02d}.tex"
        render_markdown(source_root, source_root / "manuscript" / manuscript, rendered)
        body_files.append(rendered)
    body = output / "body.tex"
    body.write_text("\n".join(f"\\input{{{path.stem}}}" for path in body_files) + "\n", encoding="utf-8")
    manuscript_text = "\n".join((source_root / "manuscript" / path).read_text(encoding="utf-8") for path in manuscripts)
    uses_tables = any("|" in line and "---" in line for line in manuscript_text.splitlines())
    uses_code = "```" in manuscript_text or "~~~" in manuscript_text
    write_metadata(output / "metadata.tex", title=args.title, subtitle=args.title, author=args.author, version=args.version, combined=args.mode == "combined", license_values=license_values, cover_name=cover_name, uses_tables=uses_tables, uses_code=uses_code)
    tex = output / "guide-template.tex"
    log = output / "guide.log"
    engine = os.environ.get("REPORTKIT_TEX_ENGINE", "pdflatex")
    report = {"schema_version": 1, "build_id": f"{args.mode}-{stamp}", "mode": args.mode, "status": "running", "started_at": datetime.now(timezone.utc).isoformat(timespec="seconds"), "inputs": [{"path": str(path), "sha256": sha256(source_root / "manuscript" / path)} for path in manuscripts], "templates": [{"path": str(path.relative_to(REPO_ROOT)), "sha256": sha256(path)} for path in (list((REPO_ROOT / "latex_templates").glob("*.cls")) + list((REPO_ROOT / "latex_templates").glob("*.sty")) + [TEMPLATE, LICENSE_FILE])], "tool_versions": {"python": sys.version.split()[0], "pandoc": version_line("pandoc"), "tex": version_line(engine)}, "commands": [], "exit_codes": [], "diagnostics": {}}
    texinputs = f"{output}:{REPO_ROOT / 'latex_templates'}:"
    for pass_number in range(1, 3):
        command = [engine, "-file-line-error", "-interaction=nonstopmode", "-halt-on-error", tex.name]
        report["commands"].append(" ".join(command))
        env = dict(os.environ, TEXINPUTS=texinputs)
        pass_log = output / f"guide-pass-{pass_number}.log"
        with pass_log.open("w", encoding="utf-8") as stream:
            stream.write("$ " + " ".join(command) + "\n")
            proc = subprocess.run(command, cwd=output, env=env, stdout=stream, stderr=subprocess.STDOUT, text=True)
        report["exit_codes"].append({"command": " ".join(command), "code": proc.returncode})
        if proc.returncode:
            report["status"] = "failed"
            (output / "build-report.json").write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
            return proc.returncode
        if pass_number == 2:
            shutil.copy2(pass_log, log)
    gate = SCRIPT_DIR / "check-build-log.py"
    gate_result = subprocess.run([sys.executable, str(gate), str(log), "--json", str(output / "diagnostics.json")], text=True)
    report["exit_codes"].append({"command": f"{sys.executable} {gate} {log}", "code": gate_result.returncode})
    report["diagnostics"] = json.loads((output / "diagnostics.json").read_text(encoding="utf-8"))
    report["gate"] = "passed" if gate_result.returncode == 0 else "failed"
    compiled_pdf = output / "guide-template.pdf"
    pdf = output / ("data-engineering-guide.pdf" if args.mode == "combined" else "section.pdf")
    if compiled_pdf.is_file() and compiled_pdf != pdf:
        shutil.copy2(compiled_pdf, pdf)
    if gate_result.returncode or not pdf.is_file():
        report["status"] = "failed"
        (output / "build-report.json").write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        return 1
    renderer = GUIDE_ROOT / "build" / ".venv" / "bin" / "python"
    if not renderer.is_file():
        renderer = Path(sys.executable)
    pages = output / "pages"
    render = subprocess.run([str(renderer), str(SCRIPT_DIR / "render_pdf_pages.py"), str(pdf), str(pages), "--manifest", str(output / "page-manifest.json")], cwd=output, text=True)
    report["exit_codes"].append({"command": f"{renderer} {SCRIPT_DIR / 'render_pdf_pages.py'} {pdf}", "code": render.returncode})
    report["page_count"] = json.loads((output / "page-manifest.json").read_text(encoding="utf-8")).get("page_count") if render.returncode == 0 else None
    inspection = subprocess.run([str(renderer), str(SCRIPT_DIR / "inspect_pdf.py"), str(pdf), "--json", str(output / "pdf-inspection.json")], cwd=output, text=True)
    report["exit_codes"].append({"command": f"{renderer} {SCRIPT_DIR / 'inspect_pdf.py'} {pdf}", "code": inspection.returncode})
    if (output / "pdf-inspection.json").is_file():
        report["pdf_inspection"] = json.loads((output / "pdf-inspection.json").read_text(encoding="utf-8"))
    report["commands"].append(f"{renderer} {SCRIPT_DIR / 'inspect_pdf.py'} {pdf}")
    report["finished_at"] = datetime.now(timezone.utc).isoformat(timespec="seconds")
    report["status"] = "passed" if render.returncode == 0 and inspection.returncode == 0 else "failed"
    (output / "build-report.json").write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return render.returncode or inspection.returncode


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--mode", choices=("section", "combined", "sections"), required=True)
    parser.add_argument("--section")
    parser.add_argument("--workers", type=int, default=1)
    parser.add_argument("--source-root")
    parser.add_argument("--version", default=os.environ.get("REPORTKIT_VERSION", "draft"))
    parser.add_argument("--title", default=os.environ.get("REPORTKIT_TITLE", "Data Engineering Guide"))
    parser.add_argument("--author", default=os.environ.get("REPORTKIT_AUTHOR", "ReportKit"))
    parser.add_argument("--cover", help="reserved for a future cover-PDF prepend")
    args = parser.parse_args()
    if args.mode == "sections":
        root = Path(args.source_root).resolve() if args.source_root else GUIDE_ROOT
        result = validate_guide(root)
        if not result.ok:
            for error in result.errors:
                print(error, file=sys.stderr)
            return 1
        failures = 0
        for entry in order_entries(root):
            if entry.startswith("00-"):
                continue
            section_args = argparse.Namespace(**vars(args))
            section_args.mode, section_args.section = "section", entry
            failures |= build(section_args)
        return failures
    return build(args)


if __name__ == "__main__":
    raise SystemExit(main())
