#!/usr/bin/env python3
"""Build guide sections and the canonical combined document.

The shell scripts in this directory are intentionally small entry points. This
module owns the shared build contract: validation, the two-pass TeX invocation,
strict final-log checking, page rendering, label checks, and build reports.
"""
from __future__ import annotations

import argparse
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, timezone
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import time
from typing import Iterable

from guide_validation import SENTINEL_RE, ValidationResult, validate_guide


SCRIPT_DIR = Path(__file__).resolve().parent
DEFAULT_ROOT = SCRIPT_DIR.parent
TEMPLATE = DEFAULT_ROOT / "templates" / "guide-template.tex"
ALLOWLIST = DEFAULT_ROOT / "config" / "build-log-allowlist.json"
RENDERER = SCRIPT_DIR / "render_pdf_pages.py"
LOG_GATE = SCRIPT_DIR / "check-build-log.py"
RENDER_VISUALS = SCRIPT_DIR / "render-visuals.sh"


class BuildFailure(RuntimeError):
    """A build failed after the report context was initialized."""


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def command_version(name: str) -> str:
    executable = shutil.which(name)
    if not executable:
        return "not found"
    try:
        proc = subprocess.run([executable, "--version"], capture_output=True, text=True, timeout=10)
        return ((proc.stdout or proc.stderr).splitlines() or [executable])[0].strip()
    except (OSError, subprocess.SubprocessError) as exc:
        return f"unavailable: {exc}"


def python_version(python: Path) -> str:
    try:
        proc = subprocess.run([str(python), "--version"], capture_output=True, text=True, timeout=10)
        return ((proc.stdout or proc.stderr).splitlines() or ["unknown"])[0].strip()
    except (OSError, subprocess.SubprocessError) as exc:
        return f"unavailable: {exc}"


def pymupdf_version(python: Path) -> str:
    code = """
try:
    import pymupdf
    print(getattr(pymupdf, 'VersionBind', getattr(pymupdf, '__version__', 'installed')))
except ImportError:
    try:
        import fitz
        print(getattr(fitz, 'VersionBind', getattr(fitz, '__doc__', 'installed')))
    except ImportError:
        print('not installed')
"""
    try:
        proc = subprocess.run([str(python), "-c", code], capture_output=True, text=True, timeout=10)
        return (proc.stdout.strip() or "not installed").splitlines()[0]
    except (OSError, subprocess.SubprocessError) as exc:
        return f"unavailable: {exc}"


def tool_versions(render_python: Path) -> dict[str, str]:
    return {
        "python": python_version(render_python),
        "PyMuPDF": pymupdf_version(render_python),
        "pandoc": command_version("pandoc"),
        "pdflatex": command_version("pdflatex"),
    }


def order_entries(root: Path) -> list[str]:
    order_file = root / "manuscript" / "order.txt"
    return [
        line.strip()
        for line in order_file.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.strip().startswith("#")
    ]


def tex_escape(value: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(char, char) for char in value)


def has_table(text: str) -> bool:
    lines = text.splitlines()
    return any(
        index + 1 < len(lines)
        and "|" in line
        and re.search(r"^\s*\|?\s*:?-{3,}", lines[index + 1])
        for index, line in enumerate(lines)
    )


def has_code(text: str) -> bool:
    return bool(re.search(r"(?m)^\s*(```|~~~)", text))


def write_metadata(
    path: Path,
    *,
    title: str,
    subtitle: str,
    author: str,
    header: str,
    footer: str,
    files: Iterable[Path],
    combined: bool,
) -> None:
    contents = "\n".join(path.read_text(encoding="utf-8") for path in files)
    lines = [
        "% Generated by guide-build.py. Do not edit.",
        "\\newif\\ifGuideUsesTables",
        "\\newif\\ifGuideUsesCode",
        "\\newif\\ifGuideIsCombined",
        "\\GuideUsesTablestrue" if has_table(contents) else "\\GuideUsesTablesfalse",
        "\\GuideUsesCodetrue" if has_code(contents) else "\\GuideUsesCodefalse",
        "\\GuideIsCombinedtrue" if combined else "\\GuideIsCombinedfalse",
        f"\\newcommand{{\\GuideTitle}}{{{tex_escape(title)}}}",
        f"\\newcommand{{\\GuideSubtitle}}{{{tex_escape(subtitle)}}}",
        f"\\newcommand{{\\GuideAuthor}}{{{tex_escape(author)}}}",
        f"\\newcommand{{\\GuideLeftHeader}}{{{tex_escape(header)}}}",
        f"\\newcommand{{\\GuideFooter}}{{{tex_escape(footer)}}}",
        "\\newcommand{\\GuideVersion}{Version 0.1}",
        "\\newcommand{\\GuideLicense}{CC BY 4.0 for original prose and diagrams; code examples and third-party assets retain separate licensing.}",
        "\\newcommand{\\GuideDisclaimer}{Educational material only. Verify examples against your systems and current documentation; this guide is not operational, financial, legal, or security advice.}",
        "\\newcommand{\\GuideProjectURL}{https://github.com/iancwm/report-kit}",
        "\\newcommand{\\GuideSubject}{Core concepts, systems, pipelines, and production practices for data engineering.}",
        "\\newcommand{\\GuideKeywords}{data engineering, data systems, pipelines, storage, orchestration, data quality}",
        f"\\newcommand{{\\GuideDate}}{{{datetime.now().strftime('%-d %B %Y')}}}",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")


def body_plan(mode: str, body_names: list[str]) -> list[str]:
    """Return the LaTeX body plan, including the combined-book front matter."""
    inputs = [f"\\input{{{name}}}" for name in body_names]
    if mode != "combined":
        return inputs
    if not body_names or body_names[0] != "00-frontmatter.tex":
        raise BuildFailure("combined build requires 00-frontmatter.md as its first manuscript")
    return [
        inputs[0],
        "\\clearpage",
        "\\phantomsection",
        "\\pdfbookmark[1]{Contents}{guide-contents}",
        "\\tableofcontents",
        "\\clearpage",
        "\\pagenumbering{arabic}",
        "\\setcounter{page}{1}",
        "\\pagestyle{fancy}",
        *inputs[1:],
    ]


def run_logged(command: list[str], *, cwd: Path, log_path: Path) -> int:
    log_path.parent.mkdir(parents=True, exist_ok=True)
    with log_path.open("w", encoding="utf-8") as log:
        log.write("$ " + " ".join(command) + "\n\n")
        proc = subprocess.run(command, cwd=cwd, stdout=log, stderr=subprocess.STDOUT, text=True)
    return proc.returncode


def validate_or_raise(root: Path) -> ValidationResult:
    result = validate_guide(root)
    if result.ok:
        return result
    message = "guide validation failed:\n" + "\n".join(f"- {error}" for error in result.errors)
    raise BuildFailure(message)


def render_body(root: Path, manuscript: Path, output: Path) -> None:
    command = ["bash", str(RENDER_VISUALS), str(manuscript), str(root / "fragments"), str(output)]
    proc = subprocess.run(command, cwd=root.parent, capture_output=True, text=True)
    if proc.returncode:
        raise BuildFailure((proc.stderr or proc.stdout).strip() or f"Pandoc failed for {manuscript}")


def copy_templates(repo_root: Path, output: Path) -> None:
    for source in [*repo_root.joinpath("latex_templates").glob("*.cls"), *repo_root.joinpath("latex_templates").glob("*.sty")]:
        shutil.copy2(source, output / source.name)
    shutil.copy2(TEMPLATE, output / "guide-template.tex")
    shutil.copy2(LOG_GATE, output / "check-build-log.py")
    shutil.copy2(ALLOWLIST, output / "build-log-allowlist.json")


def build_report_base(root: Path, mode: str, source_files: list[Path], render_python: Path, started: str) -> dict:
    repo_root = root.parent
    template_files = [TEMPLATE, ALLOWLIST, *repo_root.joinpath("latex_templates").glob("*.cls"), *repo_root.joinpath("latex_templates").glob("*.sty")]
    return {
        "schema_version": 1,
        "build_id": f"{mode}-{int(time.time())}",
        "mode": mode,
        "started_at": started,
        "finished_at": None,
        "status": "running",
        "inputs": [{"path": str(path.relative_to(root)), "sha256": sha256(path)} for path in source_files],
        "templates": [{"path": str(path.relative_to(repo_root)), "sha256": sha256(path)} for path in template_files if path.is_file()],
        "tool_versions": tool_versions(render_python),
        "commands": [],
        "diagnostics": {},
    }


def write_report(path: Path, report: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def replace_directory(temp_output: Path, final_output: Path) -> None:
    final_output.parent.mkdir(parents=True, exist_ok=True)
    if final_output.exists():
        shutil.rmtree(final_output)
    os.replace(temp_output, final_output)


def render_pages(python: Path, pdf: Path, pages: Path, report: dict, output: Path) -> dict:
    manifest = output / "page-manifest.json"
    command = [str(python), str(RENDERER), str(pdf), str(pages), "--dpi", "150", "--manifest", str(manifest)]
    report["commands"].append(" ".join(command))
    proc = subprocess.run(command, cwd=output, capture_output=True, text=True)
    if proc.returncode:
        raise BuildFailure((proc.stderr or proc.stdout).strip() or "PDF page rendering failed")
    return json.loads(manifest.read_text(encoding="utf-8"))


def assert_labels(aux_path: Path, labels: list[str]) -> None:
    if not labels:
        return
    aux = aux_path.read_text(encoding="utf-8", errors="replace")
    missing = [label for label in labels if f"\\newlabel{{{label}}}" not in aux]
    if missing:
        raise BuildFailure("PDF is missing expected figure labels: " + ", ".join(missing))


def build_one(root: Path, *, mode: str, manuscripts: list[Path], labels: list[str], output_dir: Path) -> dict:
    started = utc_now()
    render_python = root / "build" / ".venv" / "bin" / "python"
    if not render_python.is_file():
        render_python = Path(sys.executable)
    report = build_report_base(root, mode, source_files_for(root, manuscripts), render_python, started)
    report["expected_labels"] = labels
    report_path = output_dir / "build-report.json"
    temp_output = output_dir.parent / f".{output_dir.name}.run-{os.getpid()}-{time.time_ns()}"
    temp_output.mkdir(parents=True, exist_ok=False)
    try:
        copy_templates(root.parent, temp_output)
        bodies: list[Path] = []
        body_path = temp_output / "body.tex"
        for manuscript in manuscripts:
            section_body = temp_output / f"{manuscript.stem}.tex"
            render_body(root, manuscript, section_body)
            bodies.append(section_body)
        body_path.write_text("\n".join(body_plan(mode, [path.name for path in bodies])) + "\n", encoding="utf-8")
        metadata_files = manuscripts
        write_metadata(
            temp_output / "metadata.tex",
            title="A Practical Guide to Data Engineering" if mode == "combined" else "Data Engineering Guide / Section Build",
            subtitle="Core Concepts, Systems, Pipelines, and Production Practices",
            author="Data Engineering Guide",
            header="DATA ENGINEERING GUIDE" if mode == "combined" else "DATA ENGINEERING GUIDE / SECTION BUILD",
            footer="A Practical Guide to Data Engineering" if mode == "combined" else "Isolated section build for visual QA",
            files=metadata_files,
            combined=mode == "combined",
        )
        main_tex = temp_output / ("data-engineering-guide.tex" if mode == "combined" else "section.tex")
        shutil.copy2(temp_output / "guide-template.tex", main_tex)
        report["commands"].append(f"pdflatex -file-line-error -interaction=nonstopmode -halt-on-error {main_tex.name} (pass 1)")
        first_log = temp_output / "pass-1.log"
        if run_logged(["pdflatex", "-file-line-error", "-interaction=nonstopmode", "-halt-on-error", main_tex.name], cwd=temp_output, log_path=first_log):
            raise BuildFailure(f"pdflatex pass 1 failed; see {first_log}")
        report["commands"].append(f"pdflatex -file-line-error -interaction=nonstopmode -halt-on-error {main_tex.name} (pass 2)")
        second_log = temp_output / "pass-2.log"
        if run_logged(["pdflatex", "-file-line-error", "-interaction=nonstopmode", "-halt-on-error", main_tex.name], cwd=temp_output, log_path=second_log):
            raise BuildFailure(f"pdflatex pass 2 failed; see {second_log}")

        gate_json = temp_output / "log-gate.json"
        gate_command = [sys.executable, str(LOG_GATE), str(second_log), "--allowlist", str(ALLOWLIST), "--json", str(gate_json)]
        report["commands"].append(" ".join(gate_command))
        gate_proc = subprocess.run(gate_command, cwd=temp_output, capture_output=True, text=True)
        gate = json.loads(gate_json.read_text(encoding="utf-8"))
        report["diagnostics"] = gate
        if gate_proc.returncode:
            raise BuildFailure((gate_proc.stderr or gate_proc.stdout).strip() or "strict TeX log gate failed")

        pdf = temp_output / main_tex.with_suffix(".pdf").name
        pages = temp_output / "pages"
        page_manifest = render_pages(render_python, pdf, pages, report, temp_output)
        assert_labels(temp_output / main_tex.with_suffix(".aux").name, labels)
        if page_manifest["page_count"] < 1 or pdf.stat().st_size < 1:
            raise BuildFailure("build produced an empty PDF or zero pages")

        report.update(
            {
                "status": "passed",
                "pdf": {"path": str(pdf.name), "bytes": pdf.stat().st_size, "pages": page_manifest["page_count"]},
                "pages": page_manifest,
            }
        )
        report["finished_at"] = utc_now()
        report["output_dir"] = str(output_dir.relative_to(root))
        # Report is copied after the output directory is atomically replaced.
        replace_directory(temp_output, output_dir)
        write_report(report_path, report)
        return report
    except Exception as exc:
        report["status"] = "failed"
        report["error"] = str(exc)
        report["finished_at"] = utc_now()
        if temp_output.exists():
            if output_dir.exists():
                shutil.rmtree(output_dir)
            shutil.copytree(temp_output, output_dir)
            write_report(output_dir / "build-report.json", report)
            shutil.rmtree(temp_output)
        else:
            write_report(report_path, report)
        if isinstance(exc, BuildFailure):
            raise
        raise BuildFailure(str(exc)) from exc


def source_files_for(root: Path, manuscripts: list[Path]) -> list[Path]:
    return [*manuscripts, root / "manuscript" / "order.txt", *sorted((root / "fragments").glob("*.tex"))]


def labels_for_manuscripts(manuscripts: list[Path], root: Path) -> list[str]:
    labels: list[str] = []
    for manuscript in manuscripts:
        text = manuscript.read_text(encoding="utf-8")
        labels.extend(f"fig:{match.group('slug')}" for match in SENTINEL_RE.finditer(text))
    return labels


def run(root: Path, mode: str, section: str | None, workers: int) -> int:
    root = root.resolve()
    validation = validate_or_raise(root)
    entries = order_entries(root)
    if mode == "combined":
        manuscripts = [root / "manuscript" / entry for entry in entries]
        output = root / "build" / "combined"
        labels = validation.labels
        report = build_one(root, mode=mode, manuscripts=manuscripts, labels=labels, output_dir=output)
        print(f"PASS: combined guide, {report['pdf']['pages']} pages, report at {output / 'build-report.json'}")
        return 0
    if mode == "section":
        if not section:
            raise BuildFailure("section mode requires --section <manuscript path>")
        manuscript = Path(section)
        if not manuscript.is_absolute():
            manuscript = root / manuscript
        manuscript = manuscript.resolve()
        if manuscript not in [path.resolve() for path in (root / "manuscript").glob("*.md")]:
            raise BuildFailure(f"section is outside manuscript/: {section}")
        output = root / "build" / "isolated" / manuscript.stem
        labels = labels_for_manuscripts([manuscript], root)
        report = build_one(root, mode=mode, manuscripts=[manuscript], labels=labels, output_dir=output)
        print(f"PASS: section {manuscript.name}, {report['pdf']['pages']} pages, report at {output / 'build-report.json'}")
        return 0
    if mode == "sections":
        targets = [root / "manuscript" / entry for entry in entries if Path(entry).stem[:2].isdigit() and 1 <= int(Path(entry).stem[:2]) <= 9]
        workers = max(1, min(workers, len(targets) or 1))
        failures: list[str] = []
        reports: dict[str, dict] = {}
        with ThreadPoolExecutor(max_workers=workers) as executor:
            futures = {
                executor.submit(
                    build_one,
                    root,
                    mode="section",
                    manuscripts=[target],
                    labels=labels_for_manuscripts([target], root),
                    output_dir=root / "build" / "isolated" / target.stem,
                ): target
                for target in targets
            }
            for future in as_completed(futures):
                target = futures[future]
                try:
                    reports[target.name] = future.result()
                except Exception as exc:
                    failures.append(f"{target.name}: {exc}")
        for name in sorted(reports):
            print(f"PASS: section {name}, {reports[name]['pdf']['pages']} pages")
        if failures:
            for failure in sorted(failures):
                print(f"FAIL: {failure}", file=sys.stderr)
            return 1
        return 0
    raise BuildFailure(f"unknown build mode: {mode}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=DEFAULT_ROOT)
    parser.add_argument("--mode", choices=("combined", "section", "sections"), required=True)
    parser.add_argument("--section")
    parser.add_argument("--workers", type=int, default=int(os.environ.get("GUIDE_BUILD_WORKERS", "2")))
    args = parser.parse_args()
    try:
        return run(args.root, args.mode, args.section, args.workers)
    except BuildFailure as exc:
        print(f"FAIL: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
