version: 2
updates:
  - package-ecosystem: pip
    directory: /toolchain
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - toolchain
  - package-ecosystem: docker
    directory: /toolchain
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - toolchain
